name: Atlantis_Webcheck_Build

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
        name: prod
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            master:
              - 'master/**'
            scheduler:
              - 'scheduler/**'
            worker:
              - 'worker/**'
      -
        name: Checkout
        if: steps.filter.outputs.master == 'true' || steps.filter.outputs.scheduler == 'true' || steps.filter.outputs.worker == 'true'
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        if: steps.filter.outputs.master == 'true' || steps.filter.outputs.scheduler == 'true' || steps.filter.outputs.worker == 'true'
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        if: steps.filter.outputs.master == 'true' || steps.filter.outputs.scheduler == 'true' || steps.filter.outputs.worker == 'true'
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Registry
        if: steps.filter.outputs.master == 'true' || steps.filter.outputs.scheduler == 'true' || steps.filter.outputs.worker == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      -
        name: Master
        if: steps.filter.outputs.master == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./master/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/atlantishq/atlantis-webcheck-master:latest"
      -
        name: Scheduler
        if: steps.filter.outputs.scheduler == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./scheduler/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/atlantishq/atlantis-webcheck-scheduler:latest"
      -
        name: Worker
        uses: docker/build-push-action@v3
        if: steps.filter.outputs.worker == 'true'
        with:
          context: ./worker/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/atlantishq/atlantis-webcheck-worker:latest"
